version: '3'
services:
  jenkins:
    container_name: jenkins-master
    image: master
    restart: unless-stopped
    build:
      context: ./master
    ports:
      - "8080:8080"
    networks:
      - net
networks:
  net:
