version: '3'
services:
  dnsmasq:
    restart: always
    image: strm/dnsmasq:latest
    volumes:
      - ./conf/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
